// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: RoverScreenDesign

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t *ui_MainScreen;
lv_obj_t *ui_TabView;
lv_obj_t *ui_MonitorTab;
lv_obj_t *ui_Image1;
lv_obj_t *ui_HomeTab;
lv_obj_t *ui_OtherControlsPanel;
void ui_event_RPIgiveControlSwitch( lv_event_t * e);
lv_obj_t *ui_RPIgiveControlSwitch;
lv_obj_t *ui_RPIcontrolLabel;
lv_obj_t *ui_RPIpowerLabel;
lv_obj_t *ui_OpenHatchLabel;
lv_obj_t *ui_HeadRandMovLabel;
lv_obj_t *ui_EnableMotorsLabel;
void ui_event_PowerRPIswitch( lv_event_t * e);
lv_obj_t *ui_PowerRPIswitch;
void ui_event_OpenHatchSwitch( lv_event_t * e);
lv_obj_t *ui_OpenHatchSwitch;
void ui_event_HeadRandMovSwitch( lv_event_t * e);
lv_obj_t *ui_HeadRandMovSwitch;
void ui_event_EnableMotorsSwitch( lv_event_t * e);
lv_obj_t *ui_EnableMotorsSwitch;
void ui_event_HeadControlSwitch( lv_event_t * e);
lv_obj_t *ui_HeadControlSwitch;
lv_obj_t *ui_HeadControlLabel;
void ui_event_ArmControlSwitch( lv_event_t * e);
lv_obj_t *ui_ArmControlSwitch;
lv_obj_t *ui_ArmControlLabel;
lv_obj_t *ui_SelfRotationControlLabel;
void ui_event_SelfRotationControlSwitch( lv_event_t * e);
lv_obj_t *ui_SelfRotationControlSwitch;
lv_obj_t *ui_ArmServoSelectionSwitch;
lv_obj_t *ui_ControlClawServosLabel;
lv_obj_t *ui_ConfigTab;
lv_obj_t *ui_Switch2;
lv_obj_t *ui_TopPanel;
lv_obj_t *ui_SignalBar;
lv_obj_t *ui_NotificationsLabel;
lv_obj_t *ui_RcBatteryContainer;
lv_obj_t *ui_RcBatteryIcon;
lv_obj_t *ui_RcBatteryBar;
lv_obj_t *ui_RcBatteryLabel;
lv_obj_t *ui_RoverBatteryContainer;
lv_obj_t *ui_RoverBatteryIcon;
lv_obj_t *ui_RoverBatteryBar;
lv_obj_t *ui_RoverBatteryLabel;
lv_obj_t *ui_RcIcon;
lv_obj_t *ui_RoverIcon;
lv_obj_t *ui_homeIcon;
lv_obj_t *ui_monitorIcon;
lv_obj_t *ui_configIcon;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_RPIgiveControlSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      rpiGiveControlSwChecked( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      rpiGiveControlSwUnchecked( e );
}
}

void ui_event_PowerRPIswitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      powerRpiSwChecked( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      powerRpiSwUnchecked( e );
}
}

void ui_event_OpenHatchSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      openHatchSwChecked( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      openHatchSwUnchecked( e );
}
}

void ui_event_HeadRandMovSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      headRandMovSwChecked( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      headRandMovSwUnchecked( e );
}
}

void ui_event_EnableMotorsSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      enableMotorsSwChecked( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      enableMotorsSwUnchecked( e );
}
}

void ui_event_HeadControlSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      headControlSwChecked( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      headControlSwUnchecked( e );
}
}

void ui_event_ArmControlSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      armControlSwChecked( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      armControlSwUnchecked( e );
}
}

void ui_event_SelfRotationControlSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      selfRotationControlSwChecked( e );
}
if ( event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target,LV_STATE_CHECKED)  ) {
      selfRotationControlSwUnchecked( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MainScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainScreen);
}
