// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: RoverScreenDesign

#ifndef _ROVERSCREENDESIGN_UI_H
#define _ROVERSCREENDESIGN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_TabView;
extern lv_obj_t *ui_MonitorTab;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_HomeTab;
extern lv_obj_t *ui_Panel1;
void ui_event_HeadControlSwitch( lv_event_t * e);
extern lv_obj_t *ui_HeadControlSwitch;
extern lv_obj_t *ui_HeadControlLabel;
void ui_event_ArmControlSwitch( lv_event_t * e);
extern lv_obj_t *ui_ArmControlSwitch;
extern lv_obj_t *ui_ArmControlLabel;
extern lv_obj_t *ui_SelfRotationControlLabel;
void ui_event_SelfRotationControlSwitch( lv_event_t * e);
extern lv_obj_t *ui_SelfRotationControlSwitch;
extern lv_obj_t *ui_ArmServoSelectionSwitch;
extern lv_obj_t *ui_SwitchTest;
extern lv_obj_t *ui_ControlClawServosLabel;
extern lv_obj_t *ui_ConfigTab;
extern lv_obj_t *ui_Switch2;
extern lv_obj_t *ui_TopPanel;
extern lv_obj_t *ui_SignalBar;
extern lv_obj_t *ui_NotificationsLabel;
extern lv_obj_t *ui_RcBatteryContainer;
extern lv_obj_t *ui_RcBatteryIcon;
extern lv_obj_t *ui_RcBatteryBar;
extern lv_obj_t *ui_RcBatteryLabel;
extern lv_obj_t *ui_RoverBatteryContainer;
extern lv_obj_t *ui_RoverBatteryIcon;
extern lv_obj_t *ui_RoverBatteryBar;
extern lv_obj_t *ui_RoverBatteryLabel;
extern lv_obj_t *ui_RcIcon;
extern lv_obj_t *ui_RoverIcon;
extern lv_obj_t *ui_homeIcon;
extern lv_obj_t *ui_monitorIcon;
extern lv_obj_t *ui_configIcon;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_color_demo_png);   // assets/color demo.png
LV_IMG_DECLARE( ui_img_headimg_png);   // assets/headImg.png
LV_IMG_DECLARE( ui_img_roboticarmimg_png);   // assets/roboticArmImg.png
LV_IMG_DECLARE( ui_img_rotationimg_png);   // assets/rotationImg.png
LV_IMG_DECLARE( ui_img_rover_png);   // assets/rover.png
LV_IMG_DECLARE( ui_img_signalstrengthimg_png);   // assets/signalStrengthImg.png
LV_IMG_DECLARE( ui_img_batteryimg_png);   // assets/batteryImg.png
LV_IMG_DECLARE( ui_img_remoteimg_png);   // assets/remoteImg.png
LV_IMG_DECLARE( ui_img_rovericonimg_png);   // assets/roverIconImg.png
LV_IMG_DECLARE( ui_img_homeimg_png);   // assets/homeImg.png
LV_IMG_DECLARE( ui_img_monitorimg_png);   // assets/monitorImg.png
LV_IMG_DECLARE( ui_img_configimg_png);   // assets/configImg.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
