// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: RoverScreenDesign

#include "ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView = lv_tabview_create(ui_MainScreen, LV_DIR_BOTTOM, 50);
lv_obj_set_width( ui_TabView, 800);
lv_obj_set_height( ui_TabView, 445);
lv_obj_set_x( ui_TabView, 0 );
lv_obj_set_y( ui_TabView, 17 );
lv_obj_set_align( ui_TabView, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TabView, lv_color_hex(0x393839), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TabView, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView), lv_color_hex(0xFFFFFF),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView), lv_color_hex(0x292829),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView), lv_color_hex(0xFFFFFF),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView), lv_color_hex(0x595959),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_TabView), lv_color_hex(0xCACACA),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_TabView), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);

ui_MonitorTab = lv_tabview_add_tab(ui_TabView, "     Monitor");

ui_Image1 = lv_img_create(ui_MonitorTab);
lv_img_set_src(ui_Image1, &ui_img_color_demo_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 904
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 912
lv_obj_set_x( ui_Image1, -209 );
lv_obj_set_y( ui_Image1, -3 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image1,100);

ui_HomeTab = lv_tabview_add_tab(ui_TabView, "     Home");

ui_Panel1 = lv_obj_create(ui_HomeTab);
lv_obj_set_width( ui_Panel1, 113);
lv_obj_set_height( ui_Panel1, 54);
lv_obj_set_x( ui_Panel1, -291 );
lv_obj_set_y( ui_Panel1, 107 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeadControlSwitch = lv_switch_create(ui_HomeTab);
lv_obj_set_width( ui_HeadControlSwitch, 228);
lv_obj_set_height( ui_HeadControlSwitch, 198);
lv_obj_set_x( ui_HeadControlSwitch, -258 );
lv_obj_set_y( ui_HeadControlSwitch, -39 );
lv_obj_set_align( ui_HeadControlSwitch, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_HeadControlSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeadControlSwitch, &ui_img_headimg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_HeadControlSwitch, lv_color_hex(0x2A292A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HeadControlSwitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_HeadControlSwitch, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_HeadControlSwitch, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_HeadControlSwitch, &ui_img_headimg_png, LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_color(ui_HeadControlSwitch, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_opa(ui_HeadControlSwitch, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_width(ui_HeadControlSwitch, 3, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_pad(ui_HeadControlSwitch, 6, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_radius(ui_HeadControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_HeadControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 150, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0x383838), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 190, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_radius(ui_HeadControlSwitch, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_HeadControlSwitch, 0, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 0, LV_PART_KNOB| LV_STATE_CHECKED);

ui_HeadControlLabel = lv_label_create(ui_HomeTab);
lv_obj_set_width( ui_HeadControlLabel, 139);
lv_obj_set_height( ui_HeadControlLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeadControlLabel, -299 );
lv_obj_set_y( ui_HeadControlLabel, -160 );
lv_obj_set_align( ui_HeadControlLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HeadControlLabel,"Head control");
lv_obj_set_style_text_color(ui_HeadControlLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HeadControlLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HeadControlLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArmControlSwitch = lv_switch_create(ui_HomeTab);
lv_obj_set_width( ui_ArmControlSwitch, 228);
lv_obj_set_height( ui_ArmControlSwitch, 198);
lv_obj_set_x( ui_ArmControlSwitch, -1 );
lv_obj_set_y( ui_ArmControlSwitch, -38 );
lv_obj_set_align( ui_ArmControlSwitch, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_ArmControlSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_ArmControlSwitch, &ui_img_roboticarmimg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_ArmControlSwitch, lv_color_hex(0x2A292A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ArmControlSwitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ArmControlSwitch, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_ArmControlSwitch, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_ArmControlSwitch, &ui_img_roboticarmimg_png, LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_color(ui_ArmControlSwitch, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_opa(ui_ArmControlSwitch, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_width(ui_ArmControlSwitch, 3, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_pad(ui_ArmControlSwitch, 6, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_radius(ui_ArmControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_ArmControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 150, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0x383838), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 180, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_radius(ui_ArmControlSwitch, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_ArmControlSwitch, 0, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 0, LV_PART_KNOB| LV_STATE_CHECKED);

ui_ArmControlLabel = lv_label_create(ui_HomeTab);
lv_obj_set_width( ui_ArmControlLabel, 217);
lv_obj_set_height( ui_ArmControlLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ArmControlLabel, -6 );
lv_obj_set_y( ui_ArmControlLabel, -160 );
lv_obj_set_align( ui_ArmControlLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ArmControlLabel,"Robotic arm control");
lv_obj_set_style_text_color(ui_ArmControlLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ArmControlLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ArmControlLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SelfRotationControlLabel = lv_label_create(ui_HomeTab);
lv_obj_set_width( ui_SelfRotationControlLabel, 217);
lv_obj_set_height( ui_SelfRotationControlLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SelfRotationControlLabel, 255 );
lv_obj_set_y( ui_SelfRotationControlLabel, -160 );
lv_obj_set_align( ui_SelfRotationControlLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SelfRotationControlLabel,"360 degree control");
lv_obj_set_style_text_color(ui_SelfRotationControlLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SelfRotationControlLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SelfRotationControlLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SelfRotationControlSwitch = lv_switch_create(ui_HomeTab);
lv_obj_set_width( ui_SelfRotationControlSwitch, 228);
lv_obj_set_height( ui_SelfRotationControlSwitch, 198);
lv_obj_set_x( ui_SelfRotationControlSwitch, 257 );
lv_obj_set_y( ui_SelfRotationControlSwitch, -41 );
lv_obj_set_align( ui_SelfRotationControlSwitch, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_SelfRotationControlSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SelfRotationControlSwitch, &ui_img_rotationimg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_SelfRotationControlSwitch, lv_color_hex(0x2A292A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SelfRotationControlSwitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SelfRotationControlSwitch, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SelfRotationControlSwitch, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_SelfRotationControlSwitch, &ui_img_rotationimg_png, LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_color(ui_SelfRotationControlSwitch, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_opa(ui_SelfRotationControlSwitch, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_width(ui_SelfRotationControlSwitch, 3, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_pad(ui_SelfRotationControlSwitch, 6, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_radius(ui_SelfRotationControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SelfRotationControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 150, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0x383838), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 190, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_radius(ui_SelfRotationControlSwitch, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SelfRotationControlSwitch, 0, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 0, LV_PART_KNOB| LV_STATE_CHECKED);

ui_ArmServoSelectionSwitch = lv_switch_create(ui_HomeTab);
lv_obj_set_width( ui_ArmServoSelectionSwitch, 50);
lv_obj_set_height( ui_ArmServoSelectionSwitch, 25);
lv_obj_set_x( ui_ArmServoSelectionSwitch, 74 );
lv_obj_set_y( ui_ArmServoSelectionSwitch, 40 );
lv_obj_set_align( ui_ArmServoSelectionSwitch, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ArmServoSelectionSwitch, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_set_style_bg_color(ui_ArmServoSelectionSwitch, lv_color_hex(0x5A595A), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArmServoSelectionSwitch, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ArmServoSelectionSwitch, lv_color_hex(0xDC3729), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ArmServoSelectionSwitch, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_ArmServoSelectionSwitch, lv_color_hex(0xCDCACD), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArmServoSelectionSwitch, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_SwitchTest = lv_switch_create(ui_HomeTab);
lv_obj_set_width( ui_SwitchTest, 50);
lv_obj_set_height( ui_SwitchTest, 25);
lv_obj_set_x( ui_SwitchTest, -306 );
lv_obj_set_y( ui_SwitchTest, 155 );
lv_obj_set_align( ui_SwitchTest, LV_ALIGN_CENTER );
lv_obj_add_state( ui_SwitchTest, LV_STATE_CHECKED );     /// States

lv_obj_set_style_bg_color(ui_SwitchTest, lv_color_hex(0x00BA18), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SwitchTest, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_ControlClawServosLabel = lv_label_create(ui_HomeTab);
lv_obj_set_width( ui_ControlClawServosLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ControlClawServosLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ControlClawServosLabel, -29 );
lv_obj_set_y( ui_ControlClawServosLabel, 41 );
lv_obj_set_align( ui_ControlClawServosLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ControlClawServosLabel,"Control claw servos");
lv_obj_add_flag( ui_ControlClawServosLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_ConfigTab = lv_tabview_add_tab(ui_TabView, "     Config");

ui_Switch2 = lv_switch_create(ui_ConfigTab);
lv_obj_set_width( ui_Switch2, 456);
lv_obj_set_height( ui_Switch2, 304);
lv_obj_set_x( ui_Switch2, 87 );
lv_obj_set_y( ui_Switch2, -9 );
lv_obj_set_align( ui_Switch2, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Switch2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Switch2, &ui_img_rover_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_radius(ui_Switch2, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Switch2, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_Switch2, &ui_img_rover_png, LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_color(ui_Switch2, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_opa(ui_Switch2, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_width(ui_Switch2, 5, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_pad(ui_Switch2, 10, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_radius(ui_Switch2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Switch2, 0, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Switch2, 150, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_radius(ui_Switch2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Switch2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Switch2, 0, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Switch2, 0, LV_PART_KNOB| LV_STATE_CHECKED);

ui_TopPanel = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_TopPanel, 811);
lv_obj_set_height( ui_TopPanel, 63);
lv_obj_set_x( ui_TopPanel, 0 );
lv_obj_set_y( ui_TopPanel, -228 );
lv_obj_set_align( ui_TopPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TopPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TopPanel, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TopPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TopPanel, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TopPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TopPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SignalBar = lv_bar_create(ui_TopPanel);
lv_obj_set_width( ui_SignalBar, 84);
lv_obj_set_height( ui_SignalBar, 21);
lv_obj_set_x( ui_SignalBar, 229 );
lv_obj_set_y( ui_SignalBar, 29 );
lv_obj_set_align( ui_SignalBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_SignalBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SignalBar, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SignalBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SignalBar, &ui_img_signalstrengthimg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_transform_angle(ui_SignalBar, 1800, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_SignalBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SignalBar, lv_color_hex(0x292829), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SignalBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_NotificationsLabel = lv_label_create(ui_TopPanel);
lv_obj_set_width( ui_NotificationsLabel, 469);
lv_obj_set_height( ui_NotificationsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NotificationsLabel, -155 );
lv_obj_set_y( ui_NotificationsLabel, 7 );
lv_obj_set_align( ui_NotificationsLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_NotificationsLabel,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_NotificationsLabel,"The messages will be displayed here (rotating if necessary). Now it is necessary.        ");
lv_obj_set_style_text_color(ui_NotificationsLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NotificationsLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RcBatteryContainer = lv_obj_create(ui_TopPanel);
lv_obj_remove_style_all(ui_RcBatteryContainer);
lv_obj_set_width( ui_RcBatteryContainer, 158);
lv_obj_set_height( ui_RcBatteryContainer, 29);
lv_obj_set_x( ui_RcBatteryContainer, 368 );
lv_obj_set_y( ui_RcBatteryContainer, 7 );
lv_obj_set_align( ui_RcBatteryContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RcBatteryContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_RcBatteryContainer, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RcBatteryContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RcBatteryContainer, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_RcBatteryContainer, LV_BORDER_SIDE_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RcBatteryIcon = lv_img_create(ui_RcBatteryContainer);
lv_img_set_src(ui_RcBatteryIcon, &ui_img_batteryimg_png);
lv_obj_set_width( ui_RcBatteryIcon, LV_SIZE_CONTENT);  /// 44
lv_obj_set_height( ui_RcBatteryIcon, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_RcBatteryIcon, -2 );
lv_obj_set_y( ui_RcBatteryIcon, 1 );
lv_obj_set_align( ui_RcBatteryIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RcBatteryIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_RcBatteryIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_RcBatteryIcon,300);

ui_RcBatteryBar = lv_bar_create(ui_RcBatteryContainer);
lv_bar_set_value(ui_RcBatteryBar,45,LV_ANIM_OFF);
lv_bar_set_start_value(ui_RcBatteryBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_RcBatteryBar, 40);
lv_obj_set_height( ui_RcBatteryBar, 22);
lv_obj_set_x( ui_RcBatteryBar, -2 );
lv_obj_set_y( ui_RcBatteryBar, 1 );
lv_obj_set_align( ui_RcBatteryBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_RcBatteryBar, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RcBatteryBar, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RcBatteryBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_RcBatteryBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RcBatteryBar, lv_color_hex(0x00B81C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RcBatteryBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_RcBatteryLabel = lv_label_create(ui_RcBatteryContainer);
lv_obj_set_width( ui_RcBatteryLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RcBatteryLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RcBatteryLabel, -3 );
lv_obj_set_y( ui_RcBatteryLabel, 1 );
lv_obj_set_align( ui_RcBatteryLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RcBatteryLabel,"3.9V");
lv_obj_set_style_text_color(ui_RcBatteryLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RcBatteryLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_RcBatteryLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RcBatteryLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoverBatteryContainer = lv_obj_create(ui_TopPanel);
lv_obj_remove_style_all(ui_RoverBatteryContainer);
lv_obj_set_width( ui_RoverBatteryContainer, 156);
lv_obj_set_height( ui_RoverBatteryContainer, 29);
lv_obj_set_x( ui_RoverBatteryContainer, 253 );
lv_obj_set_y( ui_RoverBatteryContainer, 7 );
lv_obj_set_align( ui_RoverBatteryContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RoverBatteryContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_RoverBatteryContainer, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoverBatteryContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoverBatteryContainer, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_RoverBatteryContainer, LV_BORDER_SIDE_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoverBatteryIcon = lv_img_create(ui_RoverBatteryContainer);
lv_img_set_src(ui_RoverBatteryIcon, &ui_img_batteryimg_png);
lv_obj_set_width( ui_RoverBatteryIcon, LV_SIZE_CONTENT);  /// 44
lv_obj_set_height( ui_RoverBatteryIcon, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_RoverBatteryIcon, -2 );
lv_obj_set_y( ui_RoverBatteryIcon, 1 );
lv_obj_set_align( ui_RoverBatteryIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoverBatteryIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_RoverBatteryIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_RoverBatteryIcon,300);

ui_RoverBatteryBar = lv_bar_create(ui_RoverBatteryContainer);
lv_bar_set_value(ui_RoverBatteryBar,75,LV_ANIM_OFF);
lv_bar_set_start_value(ui_RoverBatteryBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_RoverBatteryBar, 40);
lv_obj_set_height( ui_RoverBatteryBar, 22);
lv_obj_set_x( ui_RoverBatteryBar, -2 );
lv_obj_set_y( ui_RoverBatteryBar, 1 );
lv_obj_set_align( ui_RoverBatteryBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_RoverBatteryBar, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoverBatteryBar, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoverBatteryBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_RoverBatteryBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoverBatteryBar, lv_color_hex(0x00B81C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoverBatteryBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_RoverBatteryLabel = lv_label_create(ui_RoverBatteryContainer);
lv_obj_set_width( ui_RoverBatteryLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoverBatteryLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoverBatteryLabel, -3 );
lv_obj_set_y( ui_RoverBatteryLabel, 1 );
lv_obj_set_align( ui_RoverBatteryLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoverBatteryLabel,"4.1V");
lv_obj_set_style_text_color(ui_RoverBatteryLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RoverBatteryLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_RoverBatteryLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RoverBatteryLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RcIcon = lv_img_create(ui_TopPanel);
lv_img_set_src(ui_RcIcon, &ui_img_remoteimg_png);
lv_obj_set_width( ui_RcIcon, LV_SIZE_CONTENT);  /// 44
lv_obj_set_height( ui_RcIcon, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_RcIcon, 321 );
lv_obj_set_y( ui_RcIcon, 8 );
lv_obj_set_align( ui_RcIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RcIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_RcIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_RcIcon,200);

ui_RoverIcon = lv_img_create(ui_TopPanel);
lv_img_set_src(ui_RoverIcon, &ui_img_rovericonimg_png);
lv_obj_set_width( ui_RoverIcon, LV_SIZE_CONTENT);  /// 46
lv_obj_set_height( ui_RoverIcon, LV_SIZE_CONTENT);   /// 43
lv_obj_set_x( ui_RoverIcon, 206 );
lv_obj_set_y( ui_RoverIcon, 7 );
lv_obj_set_align( ui_RoverIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoverIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_RoverIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_RoverIcon,180);

ui_homeIcon = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_homeIcon, &ui_img_homeimg_png);
lv_obj_set_width( ui_homeIcon, LV_SIZE_CONTENT);  /// 28
lv_obj_set_height( ui_homeIcon, LV_SIZE_CONTENT);   /// 28
lv_obj_set_x( ui_homeIcon, -28 );
lv_obj_set_y( ui_homeIcon, 214 );
lv_obj_set_align( ui_homeIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_homeIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_homeIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_homeIcon,180);

ui_monitorIcon = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_monitorIcon, &ui_img_monitorimg_png);
lv_obj_set_width( ui_monitorIcon, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_monitorIcon, LV_SIZE_CONTENT);   /// 29
lv_obj_set_x( ui_monitorIcon, -302 );
lv_obj_set_y( ui_monitorIcon, 214 );
lv_obj_set_align( ui_monitorIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_monitorIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_monitorIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_monitorIcon,190);

ui_configIcon = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_configIcon, &ui_img_configimg_png);
lv_obj_set_width( ui_configIcon, LV_SIZE_CONTENT);  /// 28
lv_obj_set_height( ui_configIcon, LV_SIZE_CONTENT);   /// 28
lv_obj_set_x( ui_configIcon, 236 );
lv_obj_set_y( ui_configIcon, 214 );
lv_obj_set_align( ui_configIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_configIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_configIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_configIcon,200);

lv_obj_add_event_cb(ui_HeadControlSwitch, ui_event_HeadControlSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ArmControlSwitch, ui_event_ArmControlSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SelfRotationControlSwitch, ui_event_SelfRotationControlSwitch, LV_EVENT_ALL, NULL);

}
