// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: RoverScreenDesign

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void rpiGiveControlSwChecked(lv_event_t * e);
void rpiGiveControlSwUnchecked(lv_event_t * e);
void powerRpiSwChecked(lv_event_t * e);
void powerRpiSwUnchecked(lv_event_t * e);
void openHatchSwChecked(lv_event_t * e);
void openHatchSwUnchecked(lv_event_t * e);
void headRandMovSwChecked(lv_event_t * e);
void headRandMovSwUnchecked(lv_event_t * e);
void enableRadioRcSwChecked(lv_event_t * e);
void enableRadioRcSwUnchecked(lv_event_t * e);
void headControlSwChecked(lv_event_t * e);
void headControlSwUnchecked(lv_event_t * e);
void armControlSwChecked(lv_event_t * e);
void armControlSwUnchecked(lv_event_t * e);
void selfRotationControlSwChecked(lv_event_t * e);
void selfRotationControlSwUnchecked(lv_event_t * e);
void armServoSelectionSwChecked(lv_event_t * e);
void armServoSelectionSwUnchecked(lv_event_t * e);
void wheelSelectorReleased(lv_event_t * e);
void plusDegreeBtnClicked(lv_event_t * e);
void minusDegreeBtnClicked(lv_event_t * e);
void enableMotorsSwChecked(lv_event_t * e);
void enableMotorsSwUnchecked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
