// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: RoverScreenDesign

#include "ui.h"

lv_chart_series_t* ui_EnvDataChart_series_1 = NULL;
lv_chart_series_t* ui_EnvDataChart_series_2 = NULL;

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView = lv_tabview_create(ui_MainScreen, LV_DIR_BOTTOM, 50);
lv_obj_set_width( ui_TabView, 800);
lv_obj_set_height( ui_TabView, 445);
lv_obj_set_x( ui_TabView, 0 );
lv_obj_set_y( ui_TabView, 17 );
lv_obj_set_align( ui_TabView, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TabView, lv_color_hex(0x393839), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TabView, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView), lv_color_hex(0xFFFFFF),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView), lv_color_hex(0x292829),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView), lv_color_hex(0xFFFFFF),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView), lv_color_hex(0x595959),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_TabView), lv_color_hex(0xCACACA),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_TabView), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);

ui_MonitorTab = lv_tabview_add_tab(ui_TabView, "     Monitor");
lv_obj_set_scrollbar_mode(ui_MonitorTab, LV_SCROLLBAR_MODE_OFF);

ui_RcChannelValuesPanel = lv_obj_create(ui_MonitorTab);
lv_obj_set_width( ui_RcChannelValuesPanel, 738);
lv_obj_set_height( ui_RcChannelValuesPanel, 60);
lv_obj_set_x( ui_RcChannelValuesPanel, -2 );
lv_obj_set_y( ui_RcChannelValuesPanel, -119 );
lv_obj_set_align( ui_RcChannelValuesPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RcChannelValuesPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RcChannelValuesPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RcChannelValuesPanel, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RcChannelValuesPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RcChannelValuesPanel, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RcChannelValuesPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RcChannelValuesPanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Joystick1ValuesLabel = lv_label_create(ui_RcChannelValuesPanel);
lv_obj_set_width( ui_Joystick1ValuesLabel, 168);
lv_obj_set_height( ui_Joystick1ValuesLabel, 39);
lv_obj_set_x( ui_Joystick1ValuesLabel, -275 );
lv_obj_set_y( ui_Joystick1ValuesLabel, 0 );
lv_obj_set_align( ui_Joystick1ValuesLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_Joystick1ValuesLabel,"X1					Y1");
lv_obj_set_style_text_color(ui_Joystick1ValuesLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Joystick1ValuesLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Joystick1ValuesLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Joystick1ValuesLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Joystick1ValuesLabel, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Joystick1ValuesLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Joystick1ValuesLabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Joystick1ValuesLabel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Joystick2ValuesLabel = lv_label_create(ui_RcChannelValuesPanel);
lv_obj_set_width( ui_Joystick2ValuesLabel, 168);
lv_obj_set_height( ui_Joystick2ValuesLabel, 39);
lv_obj_set_x( ui_Joystick2ValuesLabel, -100 );
lv_obj_set_y( ui_Joystick2ValuesLabel, 0 );
lv_obj_set_align( ui_Joystick2ValuesLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_Joystick2ValuesLabel,"X2				Y2");
lv_obj_set_style_text_color(ui_Joystick2ValuesLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Joystick2ValuesLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Joystick2ValuesLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Joystick2ValuesLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Joystick2ValuesLabel, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Joystick2ValuesLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Joystick2ValuesLabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Joystick2ValuesLabel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AuxValuesLabel = lv_label_create(ui_RcChannelValuesPanel);
lv_obj_set_width( ui_AuxValuesLabel, 358);
lv_obj_set_height( ui_AuxValuesLabel, 35);
lv_obj_set_x( ui_AuxValuesLabel, 175 );
lv_obj_set_y( ui_AuxValuesLabel, 0 );
lv_obj_set_align( ui_AuxValuesLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AuxValuesLabel,"AUX1					AUX2					AUX3					AUX4");
lv_obj_set_style_text_color(ui_AuxValuesLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AuxValuesLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AuxValuesLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AuxValuesLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_JoyX1valueLabel = lv_label_create(ui_RcChannelValuesPanel);
lv_obj_set_width( ui_JoyX1valueLabel, 36);
lv_obj_set_height( ui_JoyX1valueLabel, 15);
lv_obj_set_x( ui_JoyX1valueLabel, -306 );
lv_obj_set_y( ui_JoyX1valueLabel, 10 );
lv_obj_set_align( ui_JoyX1valueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_JoyX1valueLabel,"1023");
lv_obj_set_style_text_color(ui_JoyX1valueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_JoyX1valueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_JoyX1valueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_JoyX1valueLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_JoyY1valueLabel = lv_label_create(ui_RcChannelValuesPanel);
lv_obj_set_width( ui_JoyY1valueLabel, 36);
lv_obj_set_height( ui_JoyY1valueLabel, 15);
lv_obj_set_x( ui_JoyY1valueLabel, -245 );
lv_obj_set_y( ui_JoyY1valueLabel, 10 );
lv_obj_set_align( ui_JoyY1valueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_JoyY1valueLabel,"1023");
lv_obj_set_style_text_color(ui_JoyY1valueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_JoyY1valueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_JoyY1valueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_JoyY1valueLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_JoyX2valueLabel = lv_label_create(ui_RcChannelValuesPanel);
lv_obj_set_width( ui_JoyX2valueLabel, 36);
lv_obj_set_height( ui_JoyX2valueLabel, 15);
lv_obj_set_x( ui_JoyX2valueLabel, -129 );
lv_obj_set_y( ui_JoyX2valueLabel, 11 );
lv_obj_set_align( ui_JoyX2valueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_JoyX2valueLabel,"1023");
lv_obj_set_style_text_color(ui_JoyX2valueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_JoyX2valueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_JoyX2valueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_JoyX2valueLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_JoyY2valueLabel = lv_label_create(ui_RcChannelValuesPanel);
lv_obj_set_width( ui_JoyY2valueLabel, 36);
lv_obj_set_height( ui_JoyY2valueLabel, 15);
lv_obj_set_x( ui_JoyY2valueLabel, -73 );
lv_obj_set_y( ui_JoyY2valueLabel, 11 );
lv_obj_set_align( ui_JoyY2valueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_JoyY2valueLabel,"1023");
lv_obj_set_style_text_color(ui_JoyY2valueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_JoyY2valueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_JoyY2valueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_JoyY2valueLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AUX1valueLabel = lv_label_create(ui_RcChannelValuesPanel);
lv_obj_set_width( ui_AUX1valueLabel, 36);
lv_obj_set_height( ui_AUX1valueLabel, 15);
lv_obj_set_x( ui_AUX1valueLabel, 42 );
lv_obj_set_y( ui_AUX1valueLabel, 11 );
lv_obj_set_align( ui_AUX1valueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AUX1valueLabel,"1");
lv_obj_set_style_text_color(ui_AUX1valueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AUX1valueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AUX1valueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AUX1valueLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AUX2valueLabel = lv_label_create(ui_RcChannelValuesPanel);
lv_obj_set_width( ui_AUX2valueLabel, 36);
lv_obj_set_height( ui_AUX2valueLabel, 15);
lv_obj_set_x( ui_AUX2valueLabel, 128 );
lv_obj_set_y( ui_AUX2valueLabel, 11 );
lv_obj_set_align( ui_AUX2valueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AUX2valueLabel,"1");
lv_obj_set_style_text_color(ui_AUX2valueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AUX2valueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AUX2valueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AUX2valueLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AUX3valueLabel = lv_label_create(ui_RcChannelValuesPanel);
lv_obj_set_width( ui_AUX3valueLabel, 36);
lv_obj_set_height( ui_AUX3valueLabel, 15);
lv_obj_set_x( ui_AUX3valueLabel, 216 );
lv_obj_set_y( ui_AUX3valueLabel, 12 );
lv_obj_set_align( ui_AUX3valueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AUX3valueLabel,"255");
lv_obj_set_style_text_color(ui_AUX3valueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AUX3valueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AUX3valueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AUX3valueLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AUX4valueLabel = lv_label_create(ui_RcChannelValuesPanel);
lv_obj_set_width( ui_AUX4valueLabel, 36);
lv_obj_set_height( ui_AUX4valueLabel, 15);
lv_obj_set_x( ui_AUX4valueLabel, 304 );
lv_obj_set_y( ui_AUX4valueLabel, 12 );
lv_obj_set_align( ui_AUX4valueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AUX4valueLabel,"1");
lv_obj_set_style_text_color(ui_AUX4valueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AUX4valueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AUX4valueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AUX4valueLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EnvMonitorPanel = lv_obj_create(ui_MonitorTab);
lv_obj_set_width( ui_EnvMonitorPanel, 364);
lv_obj_set_height( ui_EnvMonitorPanel, 232);
lv_obj_set_x( ui_EnvMonitorPanel, -188 );
lv_obj_set_y( ui_EnvMonitorPanel, 65 );
lv_obj_set_align( ui_EnvMonitorPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_EnvMonitorPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_EnvMonitorPanel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_radius(ui_EnvMonitorPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_EnvMonitorPanel, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_EnvMonitorPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_EnvMonitorPanel, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_EnvMonitorPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_EnvMonitorPanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempArc = lv_arc_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_TempArc, 80);
lv_obj_set_height( ui_TempArc, 80);
lv_obj_set_x( ui_TempArc, -51 );
lv_obj_set_y( ui_TempArc, -64 );
lv_obj_set_align( ui_TempArc, LV_ALIGN_CENTER );
lv_obj_add_state( ui_TempArc, LV_STATE_DISABLED );     /// States
lv_arc_set_range(ui_TempArc, -20,80);
lv_arc_set_value(ui_TempArc, 30);
lv_obj_set_style_arc_color(ui_TempArc, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TempArc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_TempArc, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_TempArc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_TempArc, lv_color_hex(0xD65353), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TempArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_TempArc, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_TempArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_CurrentEnvDataLabel = lv_label_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_CurrentEnvDataLabel, 82);
lv_obj_set_height( ui_CurrentEnvDataLabel, 83);
lv_obj_set_x( ui_CurrentEnvDataLabel, -142 );
lv_obj_set_y( ui_CurrentEnvDataLabel, -64 );
lv_obj_set_align( ui_CurrentEnvDataLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CurrentEnvDataLabel,"\nCurrent\ndata");
lv_obj_set_style_text_color(ui_CurrentEnvDataLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CurrentEnvDataLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CurrentEnvDataLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CurrentEnvDataLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CurrentEnvDataLabel, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CurrentEnvDataLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CurrentEnvDataLabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_CurrentEnvDataLabel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EnvDataChart = lv_chart_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_EnvDataChart, 290);
lv_obj_set_height( ui_EnvDataChart, 114);
lv_obj_set_x( ui_EnvDataChart, -1 );
lv_obj_set_y( ui_EnvDataChart, 48 );
lv_obj_set_align( ui_EnvDataChart, LV_ALIGN_CENTER );
lv_chart_set_type( ui_EnvDataChart, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_EnvDataChart, 30);
lv_chart_set_range( ui_EnvDataChart, LV_CHART_AXIS_PRIMARY_Y, 0, 40);
lv_chart_set_div_line_count( ui_EnvDataChart, 5, 7);
lv_chart_set_axis_tick( ui_EnvDataChart, LV_CHART_AXIS_PRIMARY_X, 0, 0, 7, 2, false, 50);
lv_chart_set_axis_tick( ui_EnvDataChart, LV_CHART_AXIS_PRIMARY_Y, 5, 3, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_EnvDataChart, LV_CHART_AXIS_SECONDARY_Y, 5, 3, 5, 2, true, 25);
ui_EnvDataChart_series_1 = lv_chart_add_series(ui_EnvDataChart, lv_color_hex(0xD55052), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_EnvDataChart_series_1_array[] = { 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5 };
lv_chart_set_ext_y_array(ui_EnvDataChart, ui_EnvDataChart_series_1, ui_EnvDataChart_series_1_array);
ui_EnvDataChart_series_2 = lv_chart_add_series(ui_EnvDataChart, lv_color_hex(0x296DC5), LV_CHART_AXIS_SECONDARY_Y);
static lv_coord_t ui_EnvDataChart_series_2_array[] = { 13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13 };
lv_chart_set_ext_y_array(ui_EnvDataChart, ui_EnvDataChart_series_2, ui_EnvDataChart_series_2_array);
lv_obj_set_style_bg_color(ui_EnvDataChart, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_EnvDataChart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_color(ui_EnvDataChart, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_EnvDataChart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_set_style_bg_color(ui_EnvDataChart, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_EnvDataChart, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_line_color(ui_EnvDataChart, lv_color_hex(0x292829), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_EnvDataChart, 255, LV_PART_TICKS| LV_STATE_DEFAULT);

ui_HumArc = lv_arc_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_HumArc, 80);
lv_obj_set_height( ui_HumArc, 80);
lv_obj_set_x( ui_HumArc, 39 );
lv_obj_set_y( ui_HumArc, -64 );
lv_obj_set_align( ui_HumArc, LV_ALIGN_CENTER );
lv_obj_add_state( ui_HumArc, LV_STATE_DISABLED );     /// States
lv_arc_set_value(ui_HumArc, 50);
lv_obj_set_style_arc_color(ui_HumArc, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HumArc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_HumArc, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_HumArc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HumArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_HumArc, lv_color_hex(0x2D6CC6), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HumArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_HumArc, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_HumArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HumArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_PressureArc = lv_arc_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_PressureArc, 80);
lv_obj_set_height( ui_PressureArc, 80);
lv_obj_set_x( ui_PressureArc, 129 );
lv_obj_set_y( ui_PressureArc, -65 );
lv_obj_set_align( ui_PressureArc, LV_ALIGN_CENTER );
lv_obj_add_state( ui_PressureArc, LV_STATE_DISABLED );     /// States
lv_arc_set_range(ui_PressureArc, 300,1100);
lv_arc_set_value(ui_PressureArc, 450);
lv_obj_set_style_arc_color(ui_PressureArc, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_PressureArc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_PressureArc, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_PressureArc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PressureArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_PressureArc, lv_color_hex(0xC1B700), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_PressureArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_PressureArc, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_PressureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PressureArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_TempValueLabel = lv_label_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_TempValueLabel, 51);
lv_obj_set_height( ui_TempValueLabel, 23);
lv_obj_set_x( ui_TempValueLabel, -52 );
lv_obj_set_y( ui_TempValueLabel, -64 );
lv_obj_set_align( ui_TempValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempValueLabel,"-18ºC");
lv_obj_set_style_text_color(ui_TempValueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TempValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempValueLabel, &ui_font_Montserrat_medium_custom, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HumValueLabel = lv_label_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_HumValueLabel, 51);
lv_obj_set_height( ui_HumValueLabel, 23);
lv_obj_set_x( ui_HumValueLabel, 40 );
lv_obj_set_y( ui_HumValueLabel, -63 );
lv_obj_set_align( ui_HumValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HumValueLabel,"100%");
lv_obj_set_style_text_color(ui_HumValueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HumValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_HumValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HumValueLabel, &ui_font_Montserrat_medium_custom, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PressureValueLabel = lv_label_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_PressureValueLabel, 66);
lv_obj_set_height( ui_PressureValueLabel, 15);
lv_obj_set_x( ui_PressureValueLabel, 130 );
lv_obj_set_y( ui_PressureValueLabel, -70 );
lv_obj_set_align( ui_PressureValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PressureValueLabel,"1100 hPa");
lv_obj_set_style_text_color(ui_PressureValueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PressureValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PressureValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PressureValueLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeightValueLabel = lv_label_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_HeightValueLabel, 51);
lv_obj_set_height( ui_HeightValueLabel, 23);
lv_obj_set_x( ui_HeightValueLabel, 130 );
lv_obj_set_y( ui_HeightValueLabel, -50 );
lv_obj_set_align( ui_HeightValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HeightValueLabel,"(1256m)");
lv_obj_set_style_text_color(ui_HeightValueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HeightValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_HeightValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HeightValueLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CentigradesSymbolLabel = lv_label_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_CentigradesSymbolLabel, 22);
lv_obj_set_height( ui_CentigradesSymbolLabel, 23);
lv_obj_set_x( ui_CentigradesSymbolLabel, -163 );
lv_obj_set_y( ui_CentigradesSymbolLabel, -10 );
lv_obj_set_align( ui_CentigradesSymbolLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CentigradesSymbolLabel,"ºC");
lv_obj_set_style_text_color(ui_CentigradesSymbolLabel, lv_color_hex(0x838383), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CentigradesSymbolLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CentigradesSymbolLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CentigradesSymbolLabel, &ui_font_Montserrat_medium_custom, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MaxMinEnvParametersLabel = lv_label_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_MaxMinEnvParametersLabel, 273);
lv_obj_set_height( ui_MaxMinEnvParametersLabel, 23);
lv_obj_set_x( ui_MaxMinEnvParametersLabel, 48 );
lv_obj_set_y( ui_MaxMinEnvParametersLabel, -24 );
lv_obj_set_align( ui_MaxMinEnvParametersLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_MaxMinEnvParametersLabel,"-20ºC	    80ºC      0%       100%     300h    1100h");
lv_obj_set_style_text_color(ui_MaxMinEnvParametersLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MaxMinEnvParametersLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MaxMinEnvParametersLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MaxMinEnvParametersLabel, &ui_font_Montserrat_medium_custom_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NowLabel = lv_label_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_NowLabel, 39);
lv_obj_set_height( ui_NowLabel, 20);
lv_obj_set_x( ui_NowLabel, 121 );
lv_obj_set_y( ui_NowLabel, 95 );
lv_obj_set_align( ui_NowLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_NowLabel,"Now");
lv_obj_set_style_text_color(ui_NowLabel, lv_color_hex(0x838183), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NowLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_NowLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_NowLabel, &ui_font_Montserrat_medium_custom, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MinusOneMinLabel = lv_label_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_MinusOneMinLabel, 51);
lv_obj_set_height( ui_MinusOneMinLabel, 20);
lv_obj_set_x( ui_MinusOneMinLabel, -116 );
lv_obj_set_y( ui_MinusOneMinLabel, 95 );
lv_obj_set_align( ui_MinusOneMinLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_MinusOneMinLabel,"-1 min");
lv_obj_set_style_text_color(ui_MinusOneMinLabel, lv_color_hex(0x838183), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MinusOneMinLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MinusOneMinLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MinusOneMinLabel, &ui_font_Montserrat_medium_custom, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PercentageSymbolLabel = lv_label_create(ui_EnvMonitorPanel);
lv_obj_set_width( ui_PercentageSymbolLabel, 22);
lv_obj_set_height( ui_PercentageSymbolLabel, 23);
lv_obj_set_x( ui_PercentageSymbolLabel, 164 );
lv_obj_set_y( ui_PercentageSymbolLabel, -10 );
lv_obj_set_align( ui_PercentageSymbolLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PercentageSymbolLabel,"%");
lv_obj_set_style_text_color(ui_PercentageSymbolLabel, lv_color_hex(0x838383), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PercentageSymbolLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_PercentageSymbolLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PercentageSymbolLabel, &ui_font_Montserrat_medium_custom, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureIcon = lv_img_create(ui_EnvMonitorPanel);
lv_img_set_src(ui_TemperatureIcon, &ui_img_tempimg_png);
lv_obj_set_width( ui_TemperatureIcon, LV_SIZE_CONTENT);  /// 19
lv_obj_set_height( ui_TemperatureIcon, LV_SIZE_CONTENT);   /// 28
lv_obj_set_x( ui_TemperatureIcon, -90 );
lv_obj_set_y( ui_TemperatureIcon, -100 );
lv_obj_set_align( ui_TemperatureIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TemperatureIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TemperatureIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_TemperatureIcon,180);

ui_PressureIcon = lv_img_create(ui_EnvMonitorPanel);
lv_img_set_src(ui_PressureIcon, &ui_img_pressureimg_png);
lv_obj_set_width( ui_PressureIcon, LV_SIZE_CONTENT);  /// 27
lv_obj_set_height( ui_PressureIcon, LV_SIZE_CONTENT);   /// 26
lv_obj_set_x( ui_PressureIcon, 89 );
lv_obj_set_y( ui_PressureIcon, -101 );
lv_obj_set_align( ui_PressureIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PressureIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_PressureIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_PressureIcon,190);

ui_HumidityIcon = lv_img_create(ui_EnvMonitorPanel);
lv_img_set_src(ui_HumidityIcon, &ui_img_humidityimg_png);
lv_obj_set_width( ui_HumidityIcon, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_HumidityIcon, LV_SIZE_CONTENT);   /// 27
lv_obj_set_x( ui_HumidityIcon, 0 );
lv_obj_set_y( ui_HumidityIcon, -100 );
lv_obj_set_align( ui_HumidityIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HumidityIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HumidityIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_HumidityIcon,190);

ui_RcChanelValuesLabel = lv_label_create(ui_MonitorTab);
lv_obj_set_width( ui_RcChanelValuesLabel, 333);
lv_obj_set_height( ui_RcChanelValuesLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RcChanelValuesLabel, -203 );
lv_obj_set_y( ui_RcChanelValuesLabel, -164 );
lv_obj_set_align( ui_RcChanelValuesLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RcChanelValuesLabel,"Radio controller channel values");
lv_obj_set_style_text_color(ui_RcChanelValuesLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RcChanelValuesLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RcChanelValuesLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RPIstatusPanel = lv_obj_create(ui_MonitorTab);
lv_obj_set_width( ui_RPIstatusPanel, 352);
lv_obj_set_height( ui_RPIstatusPanel, 119);
lv_obj_set_x( ui_RPIstatusPanel, 192 );
lv_obj_set_y( ui_RPIstatusPanel, 9 );
lv_obj_set_align( ui_RPIstatusPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RPIstatusPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RPIstatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RPIstatusPanel, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RPIstatusPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RPIstatusPanel, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RPIstatusPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RPIstatusPanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CpuTempBar = lv_bar_create(ui_RPIstatusPanel);
lv_bar_set_range(ui_CpuTempBar, 0,80);
lv_bar_set_value(ui_CpuTempBar,22,LV_ANIM_OFF);
lv_bar_set_start_value(ui_CpuTempBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_CpuTempBar, 98);
lv_obj_set_height( ui_CpuTempBar, 13);
lv_obj_set_x( ui_CpuTempBar, -92 );
lv_obj_set_y( ui_CpuTempBar, 2 );
lv_obj_set_align( ui_CpuTempBar, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_CpuTempBar, lv_color_hex(0x9C9D9C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CpuTempBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_CpuTempBar, lv_color_hex(0xD98000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CpuTempBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_OnlineStatusLabel = lv_label_create(ui_RPIstatusPanel);
lv_obj_set_width( ui_OnlineStatusLabel, 109);
lv_obj_set_height( ui_OnlineStatusLabel, 20);
lv_obj_set_x( ui_OnlineStatusLabel, -139 );
lv_obj_set_y( ui_OnlineStatusLabel, -42 );
lv_obj_set_align( ui_OnlineStatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_OnlineStatusLabel,"Offline");
lv_obj_set_style_text_color(ui_OnlineStatusLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_OnlineStatusLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_OnlineStatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_OnlineStatusLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_OnlineStatusLabel, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OnlineStatusLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OnlineStatusLabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_OnlineStatusLabel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OnlineStatusIndicatorPanel = lv_obj_create(ui_RPIstatusPanel);
lv_obj_set_width( ui_OnlineStatusIndicatorPanel, 16);
lv_obj_set_height( ui_OnlineStatusIndicatorPanel, 15);
lv_obj_set_x( ui_OnlineStatusIndicatorPanel, -101 );
lv_obj_set_y( ui_OnlineStatusIndicatorPanel, -41 );
lv_obj_set_align( ui_OnlineStatusIndicatorPanel, LV_ALIGN_CENTER );
lv_obj_add_state( ui_OnlineStatusIndicatorPanel, LV_STATE_DISABLED );     /// States
lv_obj_clear_flag( ui_OnlineStatusIndicatorPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_OnlineStatusIndicatorPanel, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OnlineStatusIndicatorPanel, lv_color_hex(0x1EC261), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OnlineStatusIndicatorPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_OnlineStatusIndicatorPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OnlineStatusIndicatorPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OnlineStatusIndicatorPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OnlineStatusIndicatorPanel, lv_color_hex(0xE8393C), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_OnlineStatusIndicatorPanel, 255, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_border_color(ui_OnlineStatusIndicatorPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_border_opa(ui_OnlineStatusIndicatorPanel, 255, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_border_width(ui_OnlineStatusIndicatorPanel, 0, LV_PART_MAIN| LV_STATE_DISABLED);

ui_CpuTempLabel = lv_label_create(ui_RPIstatusPanel);
lv_obj_set_width( ui_CpuTempLabel, 147);
lv_obj_set_height( ui_CpuTempLabel, 17);
lv_obj_set_x( ui_CpuTempLabel, -94 );
lv_obj_set_y( ui_CpuTempLabel, -17 );
lv_obj_set_align( ui_CpuTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CpuTempLabel,"CPU temperature");
lv_obj_set_style_text_color(ui_CpuTempLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CpuTempLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CpuTempLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CpuTempLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CpuMinTempLabel = lv_label_create(ui_RPIstatusPanel);
lv_obj_set_width( ui_CpuMinTempLabel, 25);
lv_obj_set_height( ui_CpuMinTempLabel, 23);
lv_obj_set_x( ui_CpuMinTempLabel, -153 );
lv_obj_set_y( ui_CpuMinTempLabel, 5 );
lv_obj_set_align( ui_CpuMinTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CpuMinTempLabel,"0ºC");
lv_obj_set_style_text_color(ui_CpuMinTempLabel, lv_color_hex(0x949494), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CpuMinTempLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CpuMinTempLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CpuMinTempLabel, &ui_font_Montserrat_medium_custom_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CpuWorkloadLabel = lv_label_create(ui_RPIstatusPanel);
lv_obj_set_width( ui_CpuWorkloadLabel, 147);
lv_obj_set_height( ui_CpuWorkloadLabel, 17);
lv_obj_set_x( ui_CpuWorkloadLabel, -92 );
lv_obj_set_y( ui_CpuWorkloadLabel, 24 );
lv_obj_set_align( ui_CpuWorkloadLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CpuWorkloadLabel,"CPU work load");
lv_obj_set_style_text_color(ui_CpuWorkloadLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CpuWorkloadLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CpuWorkloadLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CpuWorkloadLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CpuMinWorkloadLabel = lv_label_create(ui_RPIstatusPanel);
lv_obj_set_width( ui_CpuMinWorkloadLabel, 22);
lv_obj_set_height( ui_CpuMinWorkloadLabel, 17);
lv_obj_set_x( ui_CpuMinWorkloadLabel, -151 );
lv_obj_set_y( ui_CpuMinWorkloadLabel, 43 );
lv_obj_set_align( ui_CpuMinWorkloadLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CpuMinWorkloadLabel,"0%");
lv_obj_set_style_text_color(ui_CpuMinWorkloadLabel, lv_color_hex(0x949494), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CpuMinWorkloadLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CpuMinWorkloadLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CpuMinWorkloadLabel, &ui_font_Montserrat_medium_custom_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CpuWorkloadBar = lv_bar_create(ui_RPIstatusPanel);
lv_bar_set_value(ui_CpuWorkloadBar,70,LV_ANIM_OFF);
lv_bar_set_start_value(ui_CpuWorkloadBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_CpuWorkloadBar, 98);
lv_obj_set_height( ui_CpuWorkloadBar, 13);
lv_obj_set_x( ui_CpuWorkloadBar, -91 );
lv_obj_set_y( ui_CpuWorkloadBar, 43 );
lv_obj_set_align( ui_CpuWorkloadBar, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_CpuWorkloadBar, lv_color_hex(0x9C9D9C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CpuWorkloadBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_CpuWorkloadBar, lv_color_hex(0xD98000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CpuWorkloadBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_CpuTempValueLabel = lv_label_create(ui_RPIstatusPanel);
lv_obj_set_width( ui_CpuTempValueLabel, 45);
lv_obj_set_height( ui_CpuTempValueLabel, 32);
lv_obj_set_x( ui_CpuTempValueLabel, -83 );
lv_obj_set_y( ui_CpuTempValueLabel, 10 );
lv_obj_set_align( ui_CpuTempValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CpuTempValueLabel,"22ºC");
lv_obj_set_style_text_color(ui_CpuTempValueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CpuTempValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CpuTempValueLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CpuTempValueLabel, &ui_font_Montserrat_medium_custom_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RPIzeroImage = lv_img_create(ui_RPIstatusPanel);
lv_img_set_src(ui_RPIzeroImage, &ui_img_raspberryimg_png);
lv_obj_set_width( ui_RPIzeroImage, LV_SIZE_CONTENT);  /// 189
lv_obj_set_height( ui_RPIzeroImage, LV_SIZE_CONTENT);   /// 121
lv_obj_set_x( ui_RPIzeroImage, 75 );
lv_obj_set_y( ui_RPIzeroImage, 1 );
lv_obj_set_align( ui_RPIzeroImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RPIzeroImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_RPIzeroImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_RPIzeroImage,245);

ui_CpuWorkloadValueLabel = lv_label_create(ui_RPIstatusPanel);
lv_obj_set_width( ui_CpuWorkloadValueLabel, 35);
lv_obj_set_height( ui_CpuWorkloadValueLabel, 17);
lv_obj_set_x( ui_CpuWorkloadValueLabel, -87 );
lv_obj_set_y( ui_CpuWorkloadValueLabel, 43 );
lv_obj_set_align( ui_CpuWorkloadValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CpuWorkloadValueLabel,"55%");
lv_obj_set_style_text_color(ui_CpuWorkloadValueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CpuWorkloadValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CpuWorkloadValueLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CpuWorkloadValueLabel, &ui_font_Montserrat_medium_custom_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CameraStatusLabel = lv_label_create(ui_RPIstatusPanel);
lv_obj_set_width( ui_CameraStatusLabel, 128);
lv_obj_set_height( ui_CameraStatusLabel, 18);
lv_obj_set_x( ui_CameraStatusLabel, -29 );
lv_obj_set_y( ui_CameraStatusLabel, -41 );
lv_obj_set_align( ui_CameraStatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CameraStatusLabel,"Camera Off");
lv_obj_set_style_text_color(ui_CameraStatusLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CameraStatusLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CameraStatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CameraStatusLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_CameraStatusLabel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CameraStatusIndicatorPanel = lv_obj_create(ui_RPIstatusPanel);
lv_obj_set_width( ui_CameraStatusIndicatorPanel, 16);
lv_obj_set_height( ui_CameraStatusIndicatorPanel, 15);
lv_obj_set_x( ui_CameraStatusIndicatorPanel, 28 );
lv_obj_set_y( ui_CameraStatusIndicatorPanel, -41 );
lv_obj_set_align( ui_CameraStatusIndicatorPanel, LV_ALIGN_CENTER );
lv_obj_add_state( ui_CameraStatusIndicatorPanel, LV_STATE_DISABLED );     /// States
lv_obj_clear_flag( ui_CameraStatusIndicatorPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_CameraStatusIndicatorPanel, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CameraStatusIndicatorPanel, lv_color_hex(0x1EC261), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CameraStatusIndicatorPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CameraStatusIndicatorPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CameraStatusIndicatorPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_CameraStatusIndicatorPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_CameraStatusIndicatorPanel, lv_color_hex(0xE8393C), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_CameraStatusIndicatorPanel, 255, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_border_color(ui_CameraStatusIndicatorPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_border_opa(ui_CameraStatusIndicatorPanel, 255, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_border_width(ui_CameraStatusIndicatorPanel, 0, LV_PART_MAIN| LV_STATE_DISABLED);

ui_CpuMaxTempLabel = lv_label_create(ui_RPIstatusPanel);
lv_obj_set_width( ui_CpuMaxTempLabel, 32);
lv_obj_set_height( ui_CpuMaxTempLabel, 15);
lv_obj_set_x( ui_CpuMaxTempLabel, -24 );
lv_obj_set_y( ui_CpuMaxTempLabel, 1 );
lv_obj_set_align( ui_CpuMaxTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CpuMaxTempLabel,"80ºC");
lv_obj_set_style_text_color(ui_CpuMaxTempLabel, lv_color_hex(0x949494), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CpuMaxTempLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CpuMaxTempLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CpuMaxTempLabel, &ui_font_Montserrat_medium_custom_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CpuMaxWorkloadLabel = lv_label_create(ui_RPIstatusPanel);
lv_obj_set_width( ui_CpuMaxWorkloadLabel, 30);
lv_obj_set_height( ui_CpuMaxWorkloadLabel, 17);
lv_obj_set_x( ui_CpuMaxWorkloadLabel, -24 );
lv_obj_set_y( ui_CpuMaxWorkloadLabel, 43 );
lv_obj_set_align( ui_CpuMaxWorkloadLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CpuMaxWorkloadLabel,"100%");
lv_obj_set_style_text_color(ui_CpuMaxWorkloadLabel, lv_color_hex(0x949494), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CpuMaxWorkloadLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CpuMaxWorkloadLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CpuMaxWorkloadLabel, &ui_font_Montserrat_medium_custom_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedometerPanel = lv_obj_create(ui_MonitorTab);
lv_obj_set_width( ui_SpeedometerPanel, 352);
lv_obj_set_height( ui_SpeedometerPanel, 72);
lv_obj_set_x( ui_SpeedometerPanel, 192 );
lv_obj_set_y( ui_SpeedometerPanel, 145 );
lv_obj_set_align( ui_SpeedometerPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SpeedometerPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SpeedometerPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SpeedometerPanel, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SpeedometerPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SpeedometerPanel, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SpeedometerPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SpeedometerPanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedGaugeImage = lv_img_create(ui_SpeedometerPanel);
lv_img_set_src(ui_SpeedGaugeImage, &ui_img_speedimg_png);
lv_obj_set_width( ui_SpeedGaugeImage, LV_SIZE_CONTENT);  /// 57
lv_obj_set_height( ui_SpeedGaugeImage, LV_SIZE_CONTENT);   /// 55
lv_obj_set_x( ui_SpeedGaugeImage, -144 );
lv_obj_set_y( ui_SpeedGaugeImage, 0 );
lv_obj_set_align( ui_SpeedGaugeImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SpeedGaugeImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SpeedGaugeImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DistanceImage = lv_img_create(ui_SpeedometerPanel);
lv_img_set_src(ui_DistanceImage, &ui_img_distanceimg_png);
lv_obj_set_width( ui_DistanceImage, LV_SIZE_CONTENT);  /// 51
lv_obj_set_height( ui_DistanceImage, LV_SIZE_CONTENT);   /// 51
lv_obj_set_x( ui_DistanceImage, 80 );
lv_obj_set_y( ui_DistanceImage, -2 );
lv_obj_set_align( ui_DistanceImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DistanceImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_DistanceImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SpeedLabel = lv_label_create(ui_SpeedometerPanel);
lv_obj_set_width( ui_SpeedLabel, 80);
lv_obj_set_height( ui_SpeedLabel, 17);
lv_obj_set_x( ui_SpeedLabel, -75 );
lv_obj_set_y( ui_SpeedLabel, -9 );
lv_obj_set_align( ui_SpeedLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedLabel,"Speed");
lv_obj_set_style_text_color(ui_SpeedLabel, lv_color_hex(0x898889), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SpeedLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DistanceLabel = lv_label_create(ui_SpeedometerPanel);
lv_obj_set_width( ui_DistanceLabel, 80);
lv_obj_set_height( ui_DistanceLabel, 17);
lv_obj_set_x( ui_DistanceLabel, 125 );
lv_obj_set_y( ui_DistanceLabel, 17 );
lv_obj_set_align( ui_DistanceLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DistanceLabel,"Distance");
lv_obj_set_style_text_color(ui_DistanceLabel, lv_color_hex(0x808280), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DistanceLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DistanceLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DistanceLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedValueLabel = lv_label_create(ui_SpeedometerPanel);
lv_obj_set_width( ui_SpeedValueLabel, 80);
lv_obj_set_height( ui_SpeedValueLabel, 17);
lv_obj_set_x( ui_SpeedValueLabel, -81 );
lv_obj_set_y( ui_SpeedValueLabel, 13 );
lv_obj_set_align( ui_SpeedValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedValueLabel,"1.5 km/h");
lv_obj_set_style_text_color(ui_SpeedValueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SpeedValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedValueLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DistanceValueLabel = lv_label_create(ui_SpeedometerPanel);
lv_obj_set_width( ui_DistanceValueLabel, 62);
lv_obj_set_height( ui_DistanceValueLabel, 17);
lv_obj_set_x( ui_DistanceValueLabel, 130 );
lv_obj_set_y( ui_DistanceValueLabel, -1 );
lv_obj_set_align( ui_DistanceValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DistanceValueLabel,"500m");
lv_obj_set_style_text_color(ui_DistanceValueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DistanceValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DistanceValueLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DistanceValueLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WheelRoverImage = lv_img_create(ui_SpeedometerPanel);
lv_img_set_src(ui_WheelRoverImage, &ui_img_wheelrovericon_png);
lv_obj_set_width( ui_WheelRoverImage, LV_SIZE_CONTENT);  /// 54
lv_obj_set_height( ui_WheelRoverImage, LV_SIZE_CONTENT);   /// 51
lv_obj_set_x( ui_WheelRoverImage, -15 );
lv_obj_set_y( ui_WheelRoverImage, -1 );
lv_obj_set_align( ui_WheelRoverImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WheelRoverImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_WheelRoverImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_RevsLabel = lv_label_create(ui_SpeedometerPanel);
lv_obj_set_width( ui_RevsLabel, 80);
lv_obj_set_height( ui_RevsLabel, 17);
lv_obj_set_x( ui_RevsLabel, 30 );
lv_obj_set_y( ui_RevsLabel, -22 );
lv_obj_set_align( ui_RevsLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RevsLabel,"Revs");
lv_obj_set_style_text_color(ui_RevsLabel, lv_color_hex(0x898889), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RevsLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_RevsLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RevsLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RevsValueLabel = lv_label_create(ui_SpeedometerPanel);
lv_obj_set_width( ui_RevsValueLabel, 34);
lv_obj_set_height( ui_RevsValueLabel, 37);
lv_obj_set_x( ui_RevsValueLabel, 28 );
lv_obj_set_y( ui_RevsValueLabel, 7 );
lv_obj_set_align( ui_RevsValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RevsValueLabel,"15\nrpm");
lv_obj_set_style_text_color(ui_RevsValueLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RevsValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_RevsValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RevsValueLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EnvMonitorLabel = lv_label_create(ui_MonitorTab);
lv_obj_set_width( ui_EnvMonitorLabel, 333);
lv_obj_set_height( ui_EnvMonitorLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_EnvMonitorLabel, -201 );
lv_obj_set_y( ui_EnvMonitorLabel, -65 );
lv_obj_set_align( ui_EnvMonitorLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_EnvMonitorLabel,"Environmental monitorization");
lv_obj_set_style_text_color(ui_EnvMonitorLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_EnvMonitorLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_EnvMonitorLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RpiStatusTitleLabel = lv_label_create(ui_MonitorTab);
lv_obj_set_width( ui_RpiStatusTitleLabel, 333);
lv_obj_set_height( ui_RpiStatusTitleLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RpiStatusTitleLabel, 182 );
lv_obj_set_y( ui_RpiStatusTitleLabel, -64 );
lv_obj_set_align( ui_RpiStatusTitleLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RpiStatusTitleLabel,"Raspberry Pi status");
lv_obj_set_style_text_color(ui_RpiStatusTitleLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RpiStatusTitleLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RpiStatusTitleLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedometerLabel = lv_label_create(ui_MonitorTab);
lv_obj_set_width( ui_SpeedometerLabel, 333);
lv_obj_set_height( ui_SpeedometerLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedometerLabel, 183 );
lv_obj_set_y( ui_SpeedometerLabel, 93 );
lv_obj_set_align( ui_SpeedometerLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedometerLabel,"Speedometer");
lv_obj_set_style_text_color(ui_SpeedometerLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedometerLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedometerLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeTab = lv_tabview_add_tab(ui_TabView, "     Home");
lv_obj_set_scrollbar_mode(ui_HomeTab, LV_SCROLLBAR_MODE_OFF);

ui_OtherControlsPanel = lv_obj_create(ui_HomeTab);
lv_obj_set_width( ui_OtherControlsPanel, 739);
lv_obj_set_height( ui_OtherControlsPanel, 114);
lv_obj_set_x( ui_OtherControlsPanel, -2 );
lv_obj_set_y( ui_OtherControlsPanel, 126 );
lv_obj_set_align( ui_OtherControlsPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_OtherControlsPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_OtherControlsPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OtherControlsPanel, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OtherControlsPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_OtherControlsPanel, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OtherControlsPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OtherControlsPanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RPIgiveControlSwitch = lv_switch_create(ui_OtherControlsPanel);
lv_obj_set_width( ui_RPIgiveControlSwitch, 62);
lv_obj_set_height( ui_RPIgiveControlSwitch, 35);
lv_obj_set_x( ui_RPIgiveControlSwitch, -265 );
lv_obj_set_y( ui_RPIgiveControlSwitch, 25 );
lv_obj_set_align( ui_RPIgiveControlSwitch, LV_ALIGN_CENTER );
lv_obj_add_state( ui_RPIgiveControlSwitch, LV_STATE_DISABLED );     /// States

lv_obj_set_style_bg_color(ui_RPIgiveControlSwitch, lv_color_hex(0x9C9C9C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RPIgiveControlSwitch, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RPIgiveControlSwitch, lv_color_hex(0x00BA18), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_RPIgiveControlSwitch, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_RPIgiveControlSwitch, lv_color_hex(0x383838), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_RPIgiveControlSwitch, 200, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_bg_color(ui_RPIgiveControlSwitch, lv_color_hex(0x383838), LV_PART_KNOB | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_RPIgiveControlSwitch, 200, LV_PART_KNOB| LV_STATE_DISABLED);

ui_RPIcontrolLabel = lv_label_create(ui_OtherControlsPanel);
lv_obj_set_width( ui_RPIcontrolLabel, 168);
lv_obj_set_height( ui_RPIcontrolLabel, 39);
lv_obj_set_x( ui_RPIcontrolLabel, -270 );
lv_obj_set_y( ui_RPIcontrolLabel, -23 );
lv_obj_set_align( ui_RPIcontrolLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RPIcontrolLabel,"Handoff control\n to RaspberryPi");
lv_obj_set_style_text_color(ui_RPIcontrolLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RPIcontrolLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_RPIcontrolLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RPIcontrolLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RPIcontrolLabel, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RPIcontrolLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RPIcontrolLabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_RPIcontrolLabel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RPIpowerLabel = lv_label_create(ui_OtherControlsPanel);
lv_obj_set_width( ui_RPIpowerLabel, 136);
lv_obj_set_height( ui_RPIpowerLabel, 39);
lv_obj_set_x( ui_RPIpowerLabel, -118 );
lv_obj_set_y( ui_RPIpowerLabel, -22 );
lv_obj_set_align( ui_RPIpowerLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RPIpowerLabel,"Power\nRasberryPi");
lv_obj_set_style_text_color(ui_RPIpowerLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RPIpowerLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_RPIpowerLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RPIpowerLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RPIpowerLabel, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RPIpowerLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RPIpowerLabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_RPIpowerLabel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OpenHatchLabel = lv_label_create(ui_OtherControlsPanel);
lv_obj_set_width( ui_OpenHatchLabel, 134);
lv_obj_set_height( ui_OpenHatchLabel, 39);
lv_obj_set_x( ui_OpenHatchLabel, 20 );
lv_obj_set_y( ui_OpenHatchLabel, -22 );
lv_obj_set_align( ui_OpenHatchLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_OpenHatchLabel,"Open rover\nhatch");
lv_obj_set_style_text_color(ui_OpenHatchLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_OpenHatchLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_OpenHatchLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_OpenHatchLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_OpenHatchLabel, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OpenHatchLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OpenHatchLabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_OpenHatchLabel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeadRandMovLabel = lv_label_create(ui_OtherControlsPanel);
lv_obj_set_width( ui_HeadRandMovLabel, 150);
lv_obj_set_height( ui_HeadRandMovLabel, 39);
lv_obj_set_x( ui_HeadRandMovLabel, 172 );
lv_obj_set_y( ui_HeadRandMovLabel, -23 );
lv_obj_set_align( ui_HeadRandMovLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HeadRandMovLabel,"Head random movements");
lv_obj_set_style_text_color(ui_HeadRandMovLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HeadRandMovLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_HeadRandMovLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HeadRandMovLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_HeadRandMovLabel, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HeadRandMovLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_HeadRandMovLabel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_HeadRandMovLabel, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EnableRadioRcLabel = lv_label_create(ui_OtherControlsPanel);
lv_obj_set_width( ui_EnableRadioRcLabel, 128);
lv_obj_set_height( ui_EnableRadioRcLabel, 39);
lv_obj_set_x( ui_EnableRadioRcLabel, 307 );
lv_obj_set_y( ui_EnableRadioRcLabel, -23 );
lv_obj_set_align( ui_EnableRadioRcLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_EnableRadioRcLabel,"Enable\nradio RC");
lv_obj_set_style_text_color(ui_EnableRadioRcLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_EnableRadioRcLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_EnableRadioRcLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_EnableRadioRcLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PowerRPIswitch = lv_switch_create(ui_OtherControlsPanel);
lv_obj_set_width( ui_PowerRPIswitch, 62);
lv_obj_set_height( ui_PowerRPIswitch, 35);
lv_obj_set_x( ui_PowerRPIswitch, -117 );
lv_obj_set_y( ui_PowerRPIswitch, 25 );
lv_obj_set_align( ui_PowerRPIswitch, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(ui_PowerRPIswitch, lv_color_hex(0x9C9C9C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PowerRPIswitch, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PowerRPIswitch, lv_color_hex(0x00BA18), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_PowerRPIswitch, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_PowerRPIswitch, lv_color_hex(0x383838), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_PowerRPIswitch, 200, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_bg_color(ui_PowerRPIswitch, lv_color_hex(0x383838), LV_PART_KNOB | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_PowerRPIswitch, 200, LV_PART_KNOB| LV_STATE_DISABLED);

ui_OpenHatchSwitch = lv_switch_create(ui_OtherControlsPanel);
lv_obj_set_width( ui_OpenHatchSwitch, 62);
lv_obj_set_height( ui_OpenHatchSwitch, 35);
lv_obj_set_x( ui_OpenHatchSwitch, 22 );
lv_obj_set_y( ui_OpenHatchSwitch, 25 );
lv_obj_set_align( ui_OpenHatchSwitch, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(ui_OpenHatchSwitch, lv_color_hex(0x9C9C9C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OpenHatchSwitch, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OpenHatchSwitch, lv_color_hex(0x00BA18), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_OpenHatchSwitch, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_OpenHatchSwitch, lv_color_hex(0x383838), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_OpenHatchSwitch, 200, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_bg_color(ui_OpenHatchSwitch, lv_color_hex(0x383838), LV_PART_KNOB | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_OpenHatchSwitch, 200, LV_PART_KNOB| LV_STATE_DISABLED);

ui_HeadRandMovSwitch = lv_switch_create(ui_OtherControlsPanel);
lv_obj_set_width( ui_HeadRandMovSwitch, 62);
lv_obj_set_height( ui_HeadRandMovSwitch, 35);
lv_obj_set_x( ui_HeadRandMovSwitch, 172 );
lv_obj_set_y( ui_HeadRandMovSwitch, 25 );
lv_obj_set_align( ui_HeadRandMovSwitch, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(ui_HeadRandMovSwitch, lv_color_hex(0x9C9C9C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadRandMovSwitch, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeadRandMovSwitch, lv_color_hex(0x00BA18), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_HeadRandMovSwitch, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_HeadRandMovSwitch, lv_color_hex(0x383838), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_HeadRandMovSwitch, 200, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_bg_color(ui_HeadRandMovSwitch, lv_color_hex(0x383838), LV_PART_KNOB | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_HeadRandMovSwitch, 200, LV_PART_KNOB| LV_STATE_DISABLED);

ui_EnableRadioRcSwitch = lv_switch_create(ui_OtherControlsPanel);
lv_obj_set_width( ui_EnableRadioRcSwitch, 62);
lv_obj_set_height( ui_EnableRadioRcSwitch, 35);
lv_obj_set_x( ui_EnableRadioRcSwitch, 307 );
lv_obj_set_y( ui_EnableRadioRcSwitch, 24 );
lv_obj_set_align( ui_EnableRadioRcSwitch, LV_ALIGN_CENTER );

lv_obj_set_style_bg_color(ui_EnableRadioRcSwitch, lv_color_hex(0x9C9C9C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_EnableRadioRcSwitch, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_EnableRadioRcSwitch, lv_color_hex(0x00BA18), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_EnableRadioRcSwitch, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_EnableRadioRcSwitch, lv_color_hex(0x383838), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_EnableRadioRcSwitch, 200, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_bg_color(ui_EnableRadioRcSwitch, lv_color_hex(0x383838), LV_PART_KNOB | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_EnableRadioRcSwitch, 200, LV_PART_KNOB| LV_STATE_DISABLED);

ui_HeadControlSwitch = lv_switch_create(ui_HomeTab);
lv_obj_set_width( ui_HeadControlSwitch, 228);
lv_obj_set_height( ui_HeadControlSwitch, 198);
lv_obj_set_x( ui_HeadControlSwitch, -258 );
lv_obj_set_y( ui_HeadControlSwitch, -39 );
lv_obj_set_align( ui_HeadControlSwitch, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_HeadControlSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_HeadControlSwitch, &ui_img_headimg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_HeadControlSwitch, lv_color_hex(0x2A292A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HeadControlSwitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_HeadControlSwitch, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_HeadControlSwitch, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_HeadControlSwitch, &ui_img_headimg_png, LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_color(ui_HeadControlSwitch, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_opa(ui_HeadControlSwitch, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_width(ui_HeadControlSwitch, 3, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_pad(ui_HeadControlSwitch, 6, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_radius(ui_HeadControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_HeadControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 150, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0x383838), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 190, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_radius(ui_HeadControlSwitch, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_HeadControlSwitch, 0, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_HeadControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_HeadControlSwitch, 0, LV_PART_KNOB| LV_STATE_CHECKED);

ui_HeadControlLabel = lv_label_create(ui_HomeTab);
lv_obj_set_width( ui_HeadControlLabel, 139);
lv_obj_set_height( ui_HeadControlLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeadControlLabel, -299 );
lv_obj_set_y( ui_HeadControlLabel, -160 );
lv_obj_set_align( ui_HeadControlLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HeadControlLabel,"Head control");
lv_obj_set_style_text_color(ui_HeadControlLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HeadControlLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HeadControlLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ArmControlSwitch = lv_switch_create(ui_HomeTab);
lv_obj_set_width( ui_ArmControlSwitch, 228);
lv_obj_set_height( ui_ArmControlSwitch, 198);
lv_obj_set_x( ui_ArmControlSwitch, -1 );
lv_obj_set_y( ui_ArmControlSwitch, -39 );
lv_obj_set_align( ui_ArmControlSwitch, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_ArmControlSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_ArmControlSwitch, &ui_img_roboticarmimg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_ArmControlSwitch, lv_color_hex(0x2A292A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ArmControlSwitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ArmControlSwitch, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_ArmControlSwitch, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_ArmControlSwitch, &ui_img_roboticarmimg_png, LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_color(ui_ArmControlSwitch, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_opa(ui_ArmControlSwitch, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_width(ui_ArmControlSwitch, 3, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_pad(ui_ArmControlSwitch, 6, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_radius(ui_ArmControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_ArmControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 150, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0x383838), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 180, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_radius(ui_ArmControlSwitch, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_ArmControlSwitch, 0, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_ArmControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ArmControlSwitch, 0, LV_PART_KNOB| LV_STATE_CHECKED);

ui_ArmControlLabel = lv_label_create(ui_HomeTab);
lv_obj_set_width( ui_ArmControlLabel, 217);
lv_obj_set_height( ui_ArmControlLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ArmControlLabel, -6 );
lv_obj_set_y( ui_ArmControlLabel, -160 );
lv_obj_set_align( ui_ArmControlLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ArmControlLabel,"Robotic arm control");
lv_obj_set_style_text_color(ui_ArmControlLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ArmControlLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ArmControlLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SelfRotationControlLabel = lv_label_create(ui_HomeTab);
lv_obj_set_width( ui_SelfRotationControlLabel, 217);
lv_obj_set_height( ui_SelfRotationControlLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SelfRotationControlLabel, 255 );
lv_obj_set_y( ui_SelfRotationControlLabel, -160 );
lv_obj_set_align( ui_SelfRotationControlLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SelfRotationControlLabel,"360 degree control");
lv_obj_set_style_text_color(ui_SelfRotationControlLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SelfRotationControlLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SelfRotationControlLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SelfRotationControlSwitch = lv_switch_create(ui_HomeTab);
lv_obj_set_width( ui_SelfRotationControlSwitch, 228);
lv_obj_set_height( ui_SelfRotationControlSwitch, 198);
lv_obj_set_x( ui_SelfRotationControlSwitch, 257 );
lv_obj_set_y( ui_SelfRotationControlSwitch, -39 );
lv_obj_set_align( ui_SelfRotationControlSwitch, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_SelfRotationControlSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SelfRotationControlSwitch, &ui_img_rotationimg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_SelfRotationControlSwitch, lv_color_hex(0x2A292A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SelfRotationControlSwitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SelfRotationControlSwitch, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SelfRotationControlSwitch, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_SelfRotationControlSwitch, &ui_img_rotationimg_png, LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_color(ui_SelfRotationControlSwitch, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_outline_opa(ui_SelfRotationControlSwitch, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_width(ui_SelfRotationControlSwitch, 3, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_outline_pad(ui_SelfRotationControlSwitch, 6, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_radius(ui_SelfRotationControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SelfRotationControlSwitch, 0, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 150, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0x383838), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 190, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_radius(ui_SelfRotationControlSwitch, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_SelfRotationControlSwitch, 0, LV_PART_KNOB| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_SelfRotationControlSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_SelfRotationControlSwitch, 0, LV_PART_KNOB| LV_STATE_CHECKED);

ui_ArmServoSelectionSwitch = lv_switch_create(ui_HomeTab);
lv_obj_set_width( ui_ArmServoSelectionSwitch, 54);
lv_obj_set_height( ui_ArmServoSelectionSwitch, 29);
lv_obj_set_x( ui_ArmServoSelectionSwitch, 74 );
lv_obj_set_y( ui_ArmServoSelectionSwitch, 39 );
lv_obj_set_align( ui_ArmServoSelectionSwitch, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ArmServoSelectionSwitch, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_set_style_bg_color(ui_ArmServoSelectionSwitch, lv_color_hex(0x5A595A), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArmServoSelectionSwitch, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ArmServoSelectionSwitch, lv_color_hex(0xDC3729), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ArmServoSelectionSwitch, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_ArmServoSelectionSwitch, lv_color_hex(0xCDCACD), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArmServoSelectionSwitch, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_ControlClawServosLabel = lv_label_create(ui_HomeTab);
lv_obj_set_width( ui_ControlClawServosLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ControlClawServosLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ControlClawServosLabel, -32 );
lv_obj_set_y( ui_ControlClawServosLabel, 41 );
lv_obj_set_align( ui_ControlClawServosLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ControlClawServosLabel,"Control claw servos");
lv_obj_add_flag( ui_ControlClawServosLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_ConfigTab = lv_tabview_add_tab(ui_TabView, "     Config");

ui_ServosAngleTrimmerLabel = lv_label_create(ui_ConfigTab);
lv_obj_set_width( ui_ServosAngleTrimmerLabel, 333);
lv_obj_set_height( ui_ServosAngleTrimmerLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ServosAngleTrimmerLabel, -200 );
lv_obj_set_y( ui_ServosAngleTrimmerLabel, -155 );
lv_obj_set_align( ui_ServosAngleTrimmerLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ServosAngleTrimmerLabel,"Wheel servos angle trimmer");
lv_obj_set_style_text_color(ui_ServosAngleTrimmerLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ServosAngleTrimmerLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ServosAngleTrimmerLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ServosAngleTrimPanel = lv_obj_create(ui_ConfigTab);
lv_obj_set_width( ui_ServosAngleTrimPanel, 736);
lv_obj_set_height( ui_ServosAngleTrimPanel, 84);
lv_obj_set_x( ui_ServosAngleTrimPanel, 0 );
lv_obj_set_y( ui_ServosAngleTrimPanel, -90 );
lv_obj_set_align( ui_ServosAngleTrimPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ServosAngleTrimPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ServosAngleTrimPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ServosAngleTrimPanel, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServosAngleTrimPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ServosAngleTrimPanel, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ServosAngleTrimPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ServosAngleTrimPanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WheelSelectorRoller = lv_roller_create(ui_ServosAngleTrimPanel);
lv_roller_set_options( ui_WheelSelectorRoller, "Front Right\nFront Left\nBack Right\nBack Left", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_WheelSelectorRoller, 170);
lv_obj_set_height( ui_WheelSelectorRoller, 68);
lv_obj_set_x( ui_WheelSelectorRoller, -252 );
lv_obj_set_y( ui_WheelSelectorRoller, 0 );
lv_obj_set_align( ui_WheelSelectorRoller, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_WheelSelectorRoller, lv_color_hex(0x6F6E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WheelSelectorRoller, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_WheelSelectorRoller, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WheelSelectorRoller, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_WheelSelectorRoller, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_WheelSelectorRoller, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_WheelSelectorRoller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_WheelSelectorRoller, lv_color_hex(0x5A595A), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WheelSelectorRoller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_WheelSelectorRoller, lv_color_hex(0xCDCACD), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WheelSelectorRoller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_PlusDegreeButton = lv_btn_create(ui_ServosAngleTrimPanel);
lv_obj_set_width( ui_PlusDegreeButton, 56);
lv_obj_set_height( ui_PlusDegreeButton, 52);
lv_obj_set_x( ui_PlusDegreeButton, -69 );
lv_obj_set_y( ui_PlusDegreeButton, -1 );
lv_obj_set_align( ui_PlusDegreeButton, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_PlusDegreeButton, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PlusDegreeButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PlusLabel = lv_label_create(ui_PlusDegreeButton);
lv_obj_set_width( ui_PlusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PlusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_PlusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PlusLabel,"+");
lv_obj_set_style_text_color(ui_PlusLabel, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PlusLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PlusLabel, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TrimValueLabel = lv_label_create(ui_ServosAngleTrimPanel);
lv_obj_set_width( ui_TrimValueLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TrimValueLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TrimValueLabel, 48 );
lv_obj_set_y( ui_TrimValueLabel, 0 );
lv_obj_set_align( ui_TrimValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TrimValueLabel,"+2 degrees");
lv_obj_set_style_text_color(ui_TrimValueLabel, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TrimValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TrimValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TrimValueLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MinusDegreeButton = lv_btn_create(ui_ServosAngleTrimPanel);
lv_obj_set_width( ui_MinusDegreeButton, 54);
lv_obj_set_height( ui_MinusDegreeButton, 52);
lv_obj_set_x( ui_MinusDegreeButton, 168 );
lv_obj_set_y( ui_MinusDegreeButton, 0 );
lv_obj_set_align( ui_MinusDegreeButton, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_MinusDegreeButton, lv_color_hex(0xCDCACD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MinusDegreeButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MinusLabel = lv_label_create(ui_MinusDegreeButton);
lv_obj_set_width( ui_MinusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MinusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MinusLabel, -1 );
lv_obj_set_y( ui_MinusLabel, -1 );
lv_obj_set_align( ui_MinusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_MinusLabel,"-");
lv_obj_set_style_text_color(ui_MinusLabel, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MinusLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MinusLabel, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OtherConfigsLabel = lv_label_create(ui_ConfigTab);
lv_obj_set_width( ui_OtherConfigsLabel, 333);
lv_obj_set_height( ui_OtherConfigsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OtherConfigsLabel, -200 );
lv_obj_set_y( ui_OtherConfigsLabel, -16 );
lv_obj_set_align( ui_OtherConfigsLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_OtherConfigsLabel,"Other configs");
lv_obj_set_style_text_color(ui_OtherConfigsLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_OtherConfigsLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_OtherConfigsLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OtherConfigsPanel = lv_obj_create(ui_ConfigTab);
lv_obj_set_width( ui_OtherConfigsPanel, 736);
lv_obj_set_height( ui_OtherConfigsPanel, 110);
lv_obj_set_x( ui_OtherConfigsPanel, 1 );
lv_obj_set_y( ui_OtherConfigsPanel, 61 );
lv_obj_set_align( ui_OtherConfigsPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_OtherConfigsPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_OtherConfigsPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OtherConfigsPanel, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OtherConfigsPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_OtherConfigsPanel, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OtherConfigsPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OtherConfigsPanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EnableMotorsLabel = lv_label_create(ui_OtherConfigsPanel);
lv_obj_set_width( ui_EnableMotorsLabel, 128);
lv_obj_set_height( ui_EnableMotorsLabel, 39);
lv_obj_set_x( ui_EnableMotorsLabel, -303 );
lv_obj_set_y( ui_EnableMotorsLabel, -19 );
lv_obj_set_align( ui_EnableMotorsLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_EnableMotorsLabel,"Enable\nmotors");
lv_obj_set_style_text_color(ui_EnableMotorsLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_EnableMotorsLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_EnableMotorsLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_EnableMotorsLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_EnableMotorsSwitch = lv_switch_create(ui_OtherConfigsPanel);
lv_obj_set_width( ui_EnableMotorsSwitch, 62);
lv_obj_set_height( ui_EnableMotorsSwitch, 35);
lv_obj_set_x( ui_EnableMotorsSwitch, -306 );
lv_obj_set_y( ui_EnableMotorsSwitch, 23 );
lv_obj_set_align( ui_EnableMotorsSwitch, LV_ALIGN_CENTER );
lv_obj_add_state( ui_EnableMotorsSwitch, LV_STATE_CHECKED );     /// States

lv_obj_set_style_bg_color(ui_EnableMotorsSwitch, lv_color_hex(0x9C9C9C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_EnableMotorsSwitch, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_EnableMotorsSwitch, lv_color_hex(0x00BA18), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_EnableMotorsSwitch, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_EnableMotorsSwitch, lv_color_hex(0x383838), LV_PART_INDICATOR | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_EnableMotorsSwitch, 200, LV_PART_INDICATOR| LV_STATE_DISABLED);

lv_obj_set_style_bg_color(ui_EnableMotorsSwitch, lv_color_hex(0x383838), LV_PART_KNOB | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_EnableMotorsSwitch, 200, LV_PART_KNOB| LV_STATE_DISABLED);

ui_TopPanel = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_TopPanel, 811);
lv_obj_set_height( ui_TopPanel, 63);
lv_obj_set_x( ui_TopPanel, 0 );
lv_obj_set_y( ui_TopPanel, -228 );
lv_obj_set_align( ui_TopPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TopPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TopPanel, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TopPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TopPanel, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TopPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TopPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SignalBar = lv_bar_create(ui_TopPanel);
lv_obj_set_width( ui_SignalBar, 84);
lv_obj_set_height( ui_SignalBar, 21);
lv_obj_set_x( ui_SignalBar, 229 );
lv_obj_set_y( ui_SignalBar, 29 );
lv_obj_set_align( ui_SignalBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_SignalBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SignalBar, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SignalBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SignalBar, &ui_img_signalstrengthimg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_transform_angle(ui_SignalBar, 1800, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_SignalBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SignalBar, lv_color_hex(0x292829), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SignalBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_NotificationsLabel = lv_label_create(ui_TopPanel);
lv_obj_set_width( ui_NotificationsLabel, 469);
lv_obj_set_height( ui_NotificationsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_NotificationsLabel, -155 );
lv_obj_set_y( ui_NotificationsLabel, 7 );
lv_obj_set_align( ui_NotificationsLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_NotificationsLabel,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_NotificationsLabel,"The messages will be displayed here (rotating if necessary). Now it is necessary.        ");
lv_obj_set_style_text_color(ui_NotificationsLabel, lv_color_hex(0xCCC9CC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NotificationsLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RcBatteryContainer = lv_obj_create(ui_TopPanel);
lv_obj_remove_style_all(ui_RcBatteryContainer);
lv_obj_set_width( ui_RcBatteryContainer, 158);
lv_obj_set_height( ui_RcBatteryContainer, 29);
lv_obj_set_x( ui_RcBatteryContainer, 368 );
lv_obj_set_y( ui_RcBatteryContainer, 7 );
lv_obj_set_align( ui_RcBatteryContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RcBatteryContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_RcBatteryContainer, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RcBatteryContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RcBatteryContainer, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_RcBatteryContainer, LV_BORDER_SIDE_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RcBatteryIcon = lv_img_create(ui_RcBatteryContainer);
lv_img_set_src(ui_RcBatteryIcon, &ui_img_batteryimg_png);
lv_obj_set_width( ui_RcBatteryIcon, LV_SIZE_CONTENT);  /// 44
lv_obj_set_height( ui_RcBatteryIcon, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_RcBatteryIcon, -2 );
lv_obj_set_y( ui_RcBatteryIcon, 1 );
lv_obj_set_align( ui_RcBatteryIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RcBatteryIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_RcBatteryIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_RcBatteryIcon,300);

ui_RcBatteryBar = lv_bar_create(ui_RcBatteryContainer);
lv_bar_set_value(ui_RcBatteryBar,45,LV_ANIM_OFF);
lv_bar_set_start_value(ui_RcBatteryBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_RcBatteryBar, 40);
lv_obj_set_height( ui_RcBatteryBar, 22);
lv_obj_set_x( ui_RcBatteryBar, -2 );
lv_obj_set_y( ui_RcBatteryBar, 1 );
lv_obj_set_align( ui_RcBatteryBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_RcBatteryBar, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RcBatteryBar, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RcBatteryBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_RcBatteryBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RcBatteryBar, lv_color_hex(0x00B81C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RcBatteryBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_RcBatteryLabel = lv_label_create(ui_RcBatteryContainer);
lv_obj_set_width( ui_RcBatteryLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RcBatteryLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RcBatteryLabel, -3 );
lv_obj_set_y( ui_RcBatteryLabel, 1 );
lv_obj_set_align( ui_RcBatteryLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RcBatteryLabel,"3.9V");
lv_obj_set_style_text_color(ui_RcBatteryLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RcBatteryLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_RcBatteryLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RcBatteryLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoverBatteryContainer = lv_obj_create(ui_TopPanel);
lv_obj_remove_style_all(ui_RoverBatteryContainer);
lv_obj_set_width( ui_RoverBatteryContainer, 156);
lv_obj_set_height( ui_RoverBatteryContainer, 29);
lv_obj_set_x( ui_RoverBatteryContainer, 253 );
lv_obj_set_y( ui_RoverBatteryContainer, 7 );
lv_obj_set_align( ui_RoverBatteryContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RoverBatteryContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_RoverBatteryContainer, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoverBatteryContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoverBatteryContainer, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_RoverBatteryContainer, LV_BORDER_SIDE_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoverBatteryIcon = lv_img_create(ui_RoverBatteryContainer);
lv_img_set_src(ui_RoverBatteryIcon, &ui_img_batteryimg_png);
lv_obj_set_width( ui_RoverBatteryIcon, LV_SIZE_CONTENT);  /// 44
lv_obj_set_height( ui_RoverBatteryIcon, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_RoverBatteryIcon, -2 );
lv_obj_set_y( ui_RoverBatteryIcon, 1 );
lv_obj_set_align( ui_RoverBatteryIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoverBatteryIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_RoverBatteryIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_RoverBatteryIcon,300);

ui_RoverBatteryBar = lv_bar_create(ui_RoverBatteryContainer);
lv_bar_set_value(ui_RoverBatteryBar,75,LV_ANIM_OFF);
lv_bar_set_start_value(ui_RoverBatteryBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_RoverBatteryBar, 40);
lv_obj_set_height( ui_RoverBatteryBar, 22);
lv_obj_set_x( ui_RoverBatteryBar, -2 );
lv_obj_set_y( ui_RoverBatteryBar, 1 );
lv_obj_set_align( ui_RoverBatteryBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_RoverBatteryBar, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoverBatteryBar, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoverBatteryBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_RoverBatteryBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoverBatteryBar, lv_color_hex(0x00BA18), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoverBatteryBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_RoverBatteryLabel = lv_label_create(ui_RoverBatteryContainer);
lv_obj_set_width( ui_RoverBatteryLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoverBatteryLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoverBatteryLabel, -3 );
lv_obj_set_y( ui_RoverBatteryLabel, 1 );
lv_obj_set_align( ui_RoverBatteryLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RoverBatteryLabel,"4.1V");
lv_obj_set_style_text_color(ui_RoverBatteryLabel, lv_color_hex(0xDEDADE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RoverBatteryLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_RoverBatteryLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RoverBatteryLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoverIcon = lv_img_create(ui_TopPanel);
lv_img_set_src(ui_RoverIcon, &ui_img_rovericonimg_png);
lv_obj_set_width( ui_RoverIcon, LV_SIZE_CONTENT);  /// 46
lv_obj_set_height( ui_RoverIcon, LV_SIZE_CONTENT);   /// 43
lv_obj_set_x( ui_RoverIcon, 206 );
lv_obj_set_y( ui_RoverIcon, 7 );
lv_obj_set_align( ui_RoverIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RoverIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_RoverIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_RoverIcon,180);

ui_RcIcon = lv_img_create(ui_TopPanel);
lv_img_set_src(ui_RcIcon, &ui_img_rcimg_png);
lv_obj_set_width( ui_RcIcon, LV_SIZE_CONTENT);  /// 51
lv_obj_set_height( ui_RcIcon, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_RcIcon, 320 );
lv_obj_set_y( ui_RcIcon, 8 );
lv_obj_set_align( ui_RcIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RcIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_RcIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_RcIcon,175);

ui_homeIcon = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_homeIcon, &ui_img_homeimg_png);
lv_obj_set_width( ui_homeIcon, LV_SIZE_CONTENT);  /// 28
lv_obj_set_height( ui_homeIcon, LV_SIZE_CONTENT);   /// 28
lv_obj_set_x( ui_homeIcon, -28 );
lv_obj_set_y( ui_homeIcon, 214 );
lv_obj_set_align( ui_homeIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_homeIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_homeIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_homeIcon,180);

ui_monitorIcon = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_monitorIcon, &ui_img_monitorimg_png);
lv_obj_set_width( ui_monitorIcon, LV_SIZE_CONTENT);  /// 29
lv_obj_set_height( ui_monitorIcon, LV_SIZE_CONTENT);   /// 29
lv_obj_set_x( ui_monitorIcon, -302 );
lv_obj_set_y( ui_monitorIcon, 214 );
lv_obj_set_align( ui_monitorIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_monitorIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_monitorIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_monitorIcon,190);

ui_configIcon = lv_img_create(ui_MainScreen);
lv_img_set_src(ui_configIcon, &ui_img_configimg_png);
lv_obj_set_width( ui_configIcon, LV_SIZE_CONTENT);  /// 28
lv_obj_set_height( ui_configIcon, LV_SIZE_CONTENT);   /// 28
lv_obj_set_x( ui_configIcon, 236 );
lv_obj_set_y( ui_configIcon, 214 );
lv_obj_set_align( ui_configIcon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_configIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_configIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_configIcon,200);

lv_obj_add_event_cb(ui_RPIgiveControlSwitch, ui_event_RPIgiveControlSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PowerRPIswitch, ui_event_PowerRPIswitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_OpenHatchSwitch, ui_event_OpenHatchSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeadRandMovSwitch, ui_event_HeadRandMovSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_EnableRadioRcSwitch, ui_event_EnableRadioRcSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HeadControlSwitch, ui_event_HeadControlSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ArmControlSwitch, ui_event_ArmControlSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SelfRotationControlSwitch, ui_event_SelfRotationControlSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ArmServoSelectionSwitch, ui_event_ArmServoSelectionSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WheelSelectorRoller, ui_event_WheelSelectorRoller, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PlusDegreeButton, ui_event_PlusDegreeButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MinusDegreeButton, ui_event_MinusDegreeButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_EnableMotorsSwitch, ui_event_EnableMotorsSwitch, LV_EVENT_ALL, NULL);

}
